### ISSUE TITLE
高亮显示异常

### ISSUE THREAD

**Issue by AnyListen** [lionsoul2014/jcseg#10]
在elasticsearch索引中配置如下分词：
-------------------------------------------------
"analyzer": {
        "text_analyzer": {
          "type": "custom",
          "char_filter": [
            "html_strip"
          ],
          "tokenizer": "jcseg",
          "filter": [
            "lowercase",
            "tsconvert"
          ]
        },
        "complex_analyzer": {
          "type": "custom",
          "char_filter": [
            "html_strip"
          ],
          "tokenizer": "jcseg_complex",
          "filter": [
            "lowercase",
            "tsconvert"
          ]
        }
-------------------------------------------------
这时，被分析的文本如果出现html标签时，搜索结果就会出现高亮部分偏移问题，偏移字符数与html标签个数一致，如图所示：[图片地址](http://yyfm.oss-cn-qingdao.aliyuncs.com/img/galiang.jpg)

暂时未测试其他分词插件与html_strip过滤器一起使用时是否存在高亮偏移问题；

**Comment by lionsoul2014** [comment]
看到了图片，不太明白你demo图片检索输入的是什么，就“理解“？

我自己也用的es，没有出现高亮的问题，我是直接把html先去掉了然后送到es去索引，你也可以试试。

至于html_strip的高亮错误应该配置的原因，因为给定了输入流Jcseg是可以准确的返回返回词条的位置，另外尝试下term_vector=with_positions_offsets高亮机制，也就是通过词条位置的机制来高亮！

另外jcseg会自动英文转成小写，所以lowercase的filter可以不需要！

**Comment by AnyListen** [comment]
@lionsoul2014 图片检索词为“理想”；
在搜索结果第一条可以看到正文里面前面为<正>，然后这一条高亮部分全部向左偏移了2个字符；
搜索结果第二条，由于没有出现html标签，所以没有出现偏移；

直接去掉html标签固然可行；
但是jcseg与html_strip搭配情况下，应该是造成了偏移问题；

lowercase的多谢提示

**Comment by AnyListen** [comment]
@lionsoul2014 该问题先Close吧，我后面跟踪一下，看看其他分词插件是否也有同样问题；
如果其他分词插件不存在偏移问题，那jcseg还是要从自身把这个问题解决一下；
否则，就是我个人配置不规范啦；
还有就是2.0版本大概什么时候发布

**Comment by lionsoul2014** [comment]
2.0昨儿发布了

**Comment by lionsoul2014** [comment]
html_strip这个问题还得深入挖下，因为Jcseg无非就是拿到他去掉html后的字符流进行分析，得到的词条的位置自然是去掉html后的偏移位置。
在solr中配合html_strip使用是可以的！

**Comment by lionsoul2014** [comment]
行，有啥进展post一下
