### ISSUE TITLE
Jcseg是否缺少一个词性标注对应关系表

### ISSUE THREAD

**Issue by AnyListen** [lionsoul2014/jcseg#12]
如题；类似这个链接这样的
[http://www.hankcs.com/nlp/part-of-speech-tagging.html](url)

**Comment by lionsoul2014** [comment]
用的标准的词性定义：https://www.oschina.net/question/814582_115416

**Comment by lionsoul2014** [comment]
Jcseg目前的词性标注依赖于词库，词库中的词性标注数据是经过多个语料库统计得到的，准确率有待验证，另外部分词条的词性在词库中尚未标注！

**Comment by AnyListen** [comment]
晓得
