### ISSUE TITLE
请问下ISegment ASegment区别

### ISSUE THREAD

**Issue by buaanie** [lionsoul2014/jcseg#13]
一直按照最简单的默认配置使用，但是不是很明白ISegment ASegment的区别，希望解开此疑惑。。

**Comment by lionsoul2014** [comment]
ISegment是全部模式分词实现的基接口，ASegment是实现了ISegment接口的抽象类，只有ComplexSeg，SimpleSeg继承了ASegment类，其他的切分模式是直接实现的ISegment接口！
