### ISSUE TITLE
出现format error.  -ignored错误

### ISSUE THREAD

**Issue by apa7** [lionsoul2014/jcseg#14]
Word: "com" format error. -ignored
Word: "net" format error. -ignored
Word: "top" format error. -ignored
Word: "tech" format error. -ignored
Word: "org" format error. -ignored
Word: "gov" format error. -ignored
Word: "edu" format error. -ignored
Word: "mil" format error. -ignored
Word: "pub" format error. -ignored
Word: "mobi" format error. -ignored
Word: "cn" format error. -ignored
Word: "com.cn" format error. -ignored
Word: "net.cn" format error. -ignored
Word: "gov.cn" format error. -ignored
Word: "kilometer" format error(single word degree should be an integer). -ignored
Word: "刘翔" format error(single word degree should be an integer). -ignored
Word: "诸葛亮" format error(single word degree should be an integer). -ignored
1355 ERROR (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.CoreContainer Error creating core [core]: Could not load conf for core core: Can't load schema D:\dev\Tomcat\solr-server\webapps\solr\solrhome\core\conf\managed-schema: Plugin init failure for [schema.xml] fieldType "textComplex": Plugin init failure for [schema.xml] analyzer/tokenizer: Error instantiating class: 'org.lionsoul.jcseg.analyzer.v5x.JcsegTokenizerFactory'

**Comment by apa7** [comment]
这个是词库导致的吗? 昨天还可以用

**Comment by apa7** [comment]
这是在服务器启动的时候报的错,环境是tomcat8 + solr + jcseg
重点是报类似ISSUE描述以及以下这种错误.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0

**Comment by apa7** [comment]
这是在服务器启动的时候报的错,环境是tomcat8 + solr + jcseg
重点是报类似ISSUE描述以及以下这种错误.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0

**Comment by lionsoul2014** [comment]
你是下载使用了最新代码，然后词库用的是之前的旧的！
目前master分支的代码是即将发布的2.0.1的代码，词库和之前的旧词库有部分兼容问题还没解决！
有两个解决方案：
1，使用：2.0.0的代码，可以到maven下载或者使用2.0.0分支的代码：https://github.com/lionsoul2014/jcseg/tree/v2.0.0-release
2，将你的词库也使用目前最新的，因为每次升级词库也会多少有些优化

**Comment by lionsoul2014** [comment]
@apa7
