### ISSUE TITLE
ant 编译错误

### ISSUE THREAD

**Issue by ruanshanshan** [lionsoul2014/jcseg#15]
build:
     [echo] -------------Compiling Application--------------
     [echo] D:\fenci\jcseg-master/vendors/lib
    [javac] D:\fenci\jcseg-master\build.xml:72: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 109 source files to D:\fenci\jcseg-master\classes
    [javac] 警告: [options] 未与 -source 1.7 一起设置引导类路径
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegAnalyzer5X.java:5: 错误: 程序包org.apache.lucene.analysis不存在
    [javac] import org.apache.lucene.analysis.Analyzer;
    [javac]                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegAnalyzer5X.java:6: 错误: 程序包org.apache.lucene.analysis不存在
    [javac] import org.apache.lucene.analysis.Tokenizer;
    [javac]                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegAnalyzer5X.java:18: 错误: 找不到符号
    [javac] public class JcsegAnalyzer5X extends Analyzer
    [javac]                                      ^
    [javac]   符号: 类 Analyzer
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegAnalyzer5X.java:94: 错误: 找不到符号
    [javac]     protected TokenStreamComponents createComponents(String fieldName) 
    [javac]               ^
    [javac]   符号:   类 TokenStreamComponents
    [javac]   位置: 类 JcsegAnalyzer5X
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegFilter.java:5: 错误: 程序包org.apache.lucene.analysis不存在
    [javac] import org.apache.lucene.analysis.TokenFilter;
    [javac]                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegFilter.java:6: 错误: 程序包org.apache.lucene.analysis不存在
    [javac] import org.apache.lucene.analysis.TokenStream;
    [javac]                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegFilter.java:15: 错误: 找不到符号
    [javac] public class JcsegFilter extends TokenFilter 
    [javac]                                  ^
    [javac]   符号: 类 TokenFilter
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegFilter.java:20: 错误: 找不到符号
    [javac]     protected JcsegFilter(TokenStream input) 
    [javac]                           ^
    [javac]   符号:   类 TokenStream
    [javac]   位置: 类 JcsegFilter
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:5: 错误: 程序包org.apache.lucene.analysis不存在
    [javac] import org.apache.lucene.analysis.Tokenizer;
    [javac]                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:6: 错误: 程序包org.apache.lucene.analysis.tokenattributes不存在
    [javac] import org.apache.lucene.analysis.tokenattributes.CharTermAttribute;
    [javac]                                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:7: 错误: 程序包org.apache.lucene.analysis.tokenattributes不存在
    [javac] import org.apache.lucene.analysis.tokenattributes.OffsetAttribute;
    [javac]                                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:8: 错误: 程序包org.apache.lucene.analysis.tokenattributes不存在
    [javac] import org.apache.lucene.analysis.tokenattributes.TypeAttribute;
    [javac]                                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:41: 错误: 找不到符号
    [javac] public class JcsegTokenizer extends Tokenizer 
    [javac]                                     ^
    [javac]   符号: 类 Tokenizer
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:46: 错误: 找不到符号
    [javac]     private final CharTermAttribute termAtt = addAttribute(CharTermAttribute.class);
    [javac]                   ^
    [javac]   符号:   类 CharTermAttribute
    [javac]   位置: 类 JcsegTokenizer
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:47: 错误: 找不到符号
    [javac]     private final OffsetAttribute offsetAtt = addAttribute(OffsetAttribute.class);
    [javac]                   ^
    [javac]   符号:   类 OffsetAttribute
    [javac]   位置: 类 JcsegTokenizer
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizer.java:48: 错误: 找不到符号
    [javac]     private final TypeAttribute typeAtt = addAttribute(TypeAttribute.class);
    [javac]                   ^
    [javac]   符号:   类 TypeAttribute
    [javac]   位置: 类 JcsegTokenizer
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizerFactory.java:6: 错误: 程序包org.apache.lucene.analysis不存在
    [javac] import org.apache.lucene.analysis.Tokenizer;
    [javac]                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizerFactory.java:7: 错误: 程序包org.apache.lucene.analysis.util不存在
    [javac] import org.apache.lucene.analysis.util.TokenizerFactory;
    [javac]                                       ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizerFactory.java:8: 错误: 程序包org.apache.lucene.util不存在
    [javac] import org.apache.lucene.util.AttributeFactory;
    [javac]                              ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizerFactory.java:19: 错误: 找不到符号
    [javac] public class JcsegTokenizerFactory extends TokenizerFactory 
    [javac]                                            ^
    [javac]   符号: 类 TokenizerFactory
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizerFactory.java:78: 错误: 找不到符号
    [javac]     public Tokenizer create( AttributeFactory factory ) 
    [javac]                              ^
    [javac]   符号:   类 AttributeFactory
    [javac]   位置: 类 JcsegTokenizerFactory
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\analyzer\v5x\JcsegTokenizerFactory.java:78: 错误: 找不到符号
    [javac]     public Tokenizer create( AttributeFactory factory ) 
    [javac]            ^
    [javac]   符号:   类 Tokenizer
    [javac]   位置: 类 JcsegTokenizerFactory
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalysisBinderProcessor.java:3: 错误: 程序包org.elasticsearch.index.analysis不存在
    [javac] import org.elasticsearch.index.analysis.AnalysisModule;
    [javac]                                        ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalysisBinderProcessor.java:10: 错误: 程序包AnalysisModule不存在
    [javac] public class JcsegAnalysisBinderProcessor extends AnalysisModule.AnalysisBinderProcessor
    [javac]                                                                 ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalysisBinderProcessor.java:13: 错误: 找不到符号
    [javac]     @Override public void processAnalyzers(AnalyzersBindings analyzersBindings)
    [javac]                                            ^
    [javac]   符号:   类 AnalyzersBindings
    [javac]   位置: 类 JcsegAnalysisBinderProcessor
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalysisBinderProcessor.java:19: 错误: 找不到符号
    [javac]     @Override public void processTokenizers(TokenizersBindings tokenizersBindings)
    [javac]                                             ^
    [javac]   符号:   类 TokenizersBindings
    [javac]   位置: 类 JcsegAnalysisBinderProcessor
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalysisBinderProcessor.java:25: 错误: 找不到符号
    [javac]     @Override public void processTokenFilters(TokenFiltersBindings tokenFiltersBindings)
    [javac]                                               ^
    [javac]   符号:   类 TokenFiltersBindings
    [javac]   位置: 类 JcsegAnalysisBinderProcessor
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:5: 错误: 程序包org.elasticsearch.common.inject不存在
    [javac] import org.elasticsearch.common.inject.Inject;
    [javac]                                       ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:6: 错误: 程序包org.elasticsearch.common.inject.assistedinject不存在
    [javac] import org.elasticsearch.common.inject.assistedinject.Assisted;
    [javac]                                                      ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:7: 错误: 程序包org.elasticsearch.common.settings不存在
    [javac] import org.elasticsearch.common.settings.Settings;
    [javac]                                         ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:8: 错误: 程序包org.elasticsearch.env不存在
    [javac] import org.elasticsearch.env.Environment;
    [javac]                             ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:9: 错误: 程序包org.elasticsearch.index不存在
    [javac] import org.elasticsearch.index.Index;
    [javac]                               ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:10: 错误: 程序包org.elasticsearch.index.analysis不存在
    [javac] import org.elasticsearch.index.analysis.AbstractIndexAnalyzerProvider;
    [javac]                                        ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:11: 错误: 程序包org.elasticsearch.index.settings不存在
    [javac] import org.elasticsearch.index.settings.IndexSettingsService;
    [javac]                                        ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:21: 错误: 找不到符号
    [javac] public class JcsegAnalyzerProvider extends AbstractIndexAnalyzerProvider<JcsegAnalyzer5X>
    [javac]                                            ^
    [javac]   符号: 类 AbstractIndexAnalyzerProvider
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:27: 错误: 找不到符号
    [javac]     public JcsegAnalyzerProvider(Index index, IndexSettingsService indexSettingsService, 
    [javac]                                  ^
    [javac]   符号:   类 Index
    [javac]   位置: 类 JcsegAnalyzerProvider
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:27: 错误: 找不到符号
    [javac]     public JcsegAnalyzerProvider(Index index, IndexSettingsService indexSettingsService, 
    [javac]                                               ^
    [javac]   符号:   类 IndexSettingsService
    [javac]   位置: 类 JcsegAnalyzerProvider
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:28: 错误: 找不到符号
    [javac]             Environment env, @Assisted String name, @Assisted Settings settings) 
    [javac]             ^
    [javac]   符号:   类 Environment
    [javac]   位置: 类 JcsegAnalyzerProvider
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegAnalyzerProvider.java:28: 错误: 找不到符号
    [javac]             Environment env, @Assisted String name, @Assisted Settings settings) 
    [javac]                                                               ^
    [javac]   符号:   类 Settings
    [javac]   位置: 类 JcsegAnalyzerProvider
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegTokenizerFactory.java:3: 错误: 程序包org.apache.lucene.analysis不存在
    [javac] import org.apache.lucene.analysis.Tokenizer;
    [javac]                                  ^
    [javac] D:\fenci\jcseg-master\src\org\lionsoul\jcseg\elasticsearch\index\analysis\JcsegTokenizerFactory.java:4: 错误: 程序包org.elasticsearch.common.inject不存在

**Comment by lionsoul2014** [comment]
建议使用maven编译，ant编译参考：https://github.com/lionsoul2014/jcseg/tree/master/vendors/lib下的README.md需要将需要的依赖包都放入进去，最方便的方式就直接使用maven管理或者直接到maven下载对应的jar包 https://repo1.maven.org/maven2/org/lionsoul/！

**Comment by ruanshanshan** [comment]
谢谢，我在sourcecode里看到jcseg_core_1_9_9.xml（如下），也就是我现在用的是1_9_9版本，我想用最新的jar,能够提供类似的xml文件不，谢谢!
<component name="libraryTable">
  <library name="jcseg-core-1.9.9">
    <CLASSES>
      <root url="jar://$USER_HOME$/.gradle/caches/modules-2/files-2.1/org.lionsoul/jcseg-core/1.9.9/dc2e31ae9f0717237045522208a0bd95070acf09/jcseg-core-1.9.9.jar!/" />
    </CLASSES>
    <JAVADOC />
    <SOURCES>
      <root url="jar://$USER_HOME$/.gradle/caches/modules-2/files-2.1/org.lionsoul/jcseg-core/1.9.9/fb78db750d5fed0cb7f7fdf7c81e97aebad65808/jcseg-core-1.9.9-sources.jar!/" />
    </SOURCES>
  </library>
</component>

**Comment by lionsoul2014** [comment]
贴的那个xml浏览器貌似显示空白，你这个是要用在哪个地方，可以根据这个文档改一份。
有的相关的配置文档都在README.md里面都可以找到！
