### ISSUE TITLE
自定义词典构造问题

### ISSUE THREAD

**Issue by changedi** [lionsoul2014/jcseg#16]
```
/**
     * create a singleton ADictionary object according to the JcsegTaskConfig
     * 
     * @param   config
     * @param   loadDic
     * @param   ADictionary
    */
    public static ADictionary createSingletonDictionary(JcsegTaskConfig config, boolean loadDic)
    {
        synchronized (LOCK) {
            if ( singletonDic == null ) {
                singletonDic = createDefaultDictionary(config);
            }
        }
        
        return singletonDic;
    }
```

DictionaryFactory 这个代码还是执行了构造默认词典的逻辑

**Comment by lionsoul2014** [comment]
ADictionary#createSingletonDictionary是用来创建单例词库！配置通过config定制即可！

**Comment by changedi** [comment]
因为README中【2)，通过ADictionary手动加载词库：】这段里讲述的配置createSingletonDictionary的第二个参数设置false，而实际源码中第二个参数是不生效的。这样有点产生误会：）

issue closed

**Comment by lionsoul2014** [comment]
哈哈，好眼力！
`    /**
     * create a singleton ADictionary object according to the JcsegTaskConfig
     * 
     * @param   config
     * @param   loadDic
     * @param   ADictionary
    */
    public static ADictionary createSingletonDictionary(JcsegTaskConfig config, boolean loadDic)
    {
        synchronized (LOCK) {
            if ( singletonDic == null ) {
                singletonDic = createDefaultDictionary(config, loadDic);
            }
        }
        
        return singletonDic;
    }`

需要改成这样，这是一个bug，已经修复了提交了代码，感谢反馈！
