### ISSUE TITLE
使用jcseg-core-2.1.0.jar 出错

### ISSUE THREAD

**Issue by ruanshanshan** [lionsoul2014/jcseg#17]
1 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/lionsoul/jcseg/tokenizer/core/JcsegTaskConfig;
难道是因为jdk版本问题？

**Comment by lionsoul2014** [comment]
把你的使用到的地方和场景说明下，这个很大程度上是你没有引入jcseg-core包的错误！Jcseg 2.1.0版本需要jdk 8才可以运行。
