### ISSUE TITLE
停用词自定义使用

### ISSUE THREAD

**Issue by pmgod8921** [lionsoul2014/jcseg#18]
jcseg 我在自定义停用词的时候  将一个名为lex-stopword.lex 的文件加到了resource文件夹中，然后将停用词开关打开 但是在写测试类 测试的时候发现 程序将这个文件中所有自定义的词当成了自定义词库分词 而不是当做停用词  我在网上找不到具体的自定义停用词的案例 请帮忙解答一下 谢谢 

还有一个问题：
自动中英文停止词过滤功能（需要在jcseg.properties中开启该选项，lex-stopwords.lex为停止词词库）。
以上是你的说明中的一条信息 我可以理解为 只能往这个lex-stopwords.lex
[JSegTextAnalyser.txt](https://github.com/lionsoul2014/jcseg/files/703405/JSegTextAnalyser.txt)
![pic](https://cloud.githubusercontent.com/assets/25093498/21916820/fdf8205e-d97d-11e6-938e-07c32b7e3581.jpg)

文件中加入停用词么 不能自己定义个文件放入自定义停用词

**Comment by lionsoul2014** [comment]
哈哈，这个应该是算是文档说明不清楚吧！
Jcseg的词库主要通过类别来区分，词库的名称没做任何限制的，停止词你也可以弄很多词库，但是都需要在词库文件的首行增加一个词库的类别标识！
对于停止词在你的自定义词库文件第一行增加：STOP_WORD，就可以了，也可以参考下自带的停止词库：https://github.com/lionsoul2014/jcseg/blob/master/vendors/lexicon/lex-stopword.lex

**Comment by lionsoul2014** [comment]
没有增加类别标识的都会默认为主类别词库！

**Comment by pmgod8921** [comment]
我刚才重新按照 您的要求 把配置文件改了 
![image](https://cloud.githubusercontent.com/assets/25093498/21917858/12522ca4-d986-11e6-9ae2-8e646a2613ed.png)
我的测试数据是：
![image](https://cloud.githubusercontent.com/assets/25093498/21917868/28a5e770-d986-11e6-906d-9e5e39910a0c.png)

但是测试出来的结果还是有停用词：
![image](https://cloud.githubusercontent.com/assets/25093498/21917870/2e06cea0-d986-11e6-97af-4289f65f24d0.png)
我用的是关键词  然后把他换成普通的分词 方式 还是会有 我不知道是不是文件加载的时候有问题 但是程序可以跑通  麻烦帮忙看下

我用的pom版本是：
![image](https://cloud.githubusercontent.com/assets/25093498/21917879/3d232366-d986-11e6-9b13-39c7e2cad585.png)

代码文件为：
[JSegTextAnalyser.txt](https://github.com/lionsoul2014/jcseg/files/703483/JSegTextAnalyser.txt)

**Comment by pmgod8921** [comment]
你好，刚才我又尝试了一下  好像模式用错了 我问一下 是不是只有 DETECT_MODE 精准模式不走停用词啊？
DETECT_MODE ：模式的结果 没有用停用词
![image](https://cloud.githubusercontent.com/assets/25093498/21918496/cd312d80-d98c-11e6-8b37-29fa2630ca6a.png)
COMPLEX_MODE：复杂模式的结果 运用了自定义的停用词库
![image](https://cloud.githubusercontent.com/assets/25093498/21918509/f1a1f046-d98c-11e6-82d4-9e206a301e02.png)

我想问下这个问题是BUG还是当初就是这么设计的

我换了pom的包：
现在的版本是：
![image](https://cloud.githubusercontent.com/assets/25093498/21918524/221fbfdc-d98d-11e6-9162-296f06b8f5ab.png)


还有一个问题：那种模式的速度是最快的 能给解释一下么？

**Comment by lionsoul2014** [comment]
1，建议使用最新版本的2.1.0
2，仔细阅读下每个模式的解释，DETECT_MODE是检测模式，是只返回词库中有的词条，没有的词条直接过滤掉了，所以他没有停止词过滤的概念，因为如果不需要这个词条，直接不要放入词库即可。
3，对于关键字提取，建议使用复杂模式，更需要的是切分的准确率，速度不会成为你的影响。
4，从切分速度来说，Delimiter_mode > detect_mode > simple_mode > search_mode > complex_mode > NLP_MODE，理由就是里面的实现考虑程度越来越复杂，得到的是准确率的提升。

你的给的demo关键字提取如下：

```shell
jcseg~keywords>> 从小我就是第一的成绩考进了重点大学，同事们都很佩服我，他们认为孟晨最牛逼了
Top10关键词：
[大学, 同事, 重点, 考进, 佩服, 认为, 成绩, 孟晨, 第一, 就是]
Done, cost: 0.01783sec(less than)
jcseg~keywords>> 
```

**Comment by pmgod8921** [comment]
谢谢您 问题完美解决 我会继续使用这款产品 非常实用
