### ISSUE TITLE
升级2.1.0 词库格式遇到问题

### ISSUE THREAD

**Issue by pmgod8921** [lionsoul2014/jcseg#19]
我想问下是不是词库格式变化了 ，下面是报错：
![image](https://cloud.githubusercontent.com/assets/25093498/21979633/bfd450b4-dc1a-11e6-9e38-9f374b0c4624.png)

我看了您写的change文档 好像是变化了 但是没有格式说明
我的格式为：
![image](https://cloud.githubusercontent.com/assets/25093498/21979662/e3cba24c-dc1a-11e6-9879-41930a08c179.png)

用2.0.0就不会报错 我DEBUG 看了下是 ADictionary 的报错 ，是必须 词语要加上词性等3个元素么，长度只要不等于4就会有问题，不知道是不是个BUG 您帮忙看下！！！

**Comment by lionsoul2014** [comment]
之前有个问了一样的问题的issue，给了说明，你往前翻下。新版本修改了词库格式，changes.md里面也写了升级注意事项。

**Comment by lionsoul2014** [comment]
如果没有自定义词库，将词库使用最新的就OK了。如果自定义了之前的词库就合并下。词库格式参考下lexicon目录下对应类别下词库说明，变化很细微！

**Comment by pmgod8921** [comment]
我现在用的就是maven的最新版本2.1.0的版本 相比词库肯定也是最新的 上面的是我自定义的词库 我得意思 是因为我今天做了测试 加载最新词库的时候没有问题 就是加载上述格式的词库就会有上述报错  我想问下 是不是自定义的词库也要必须增加词性类似的3个元素 2.0.0是没有任何问题的 如果自定义的词必须要加词性的话 就比较麻烦 没有以前那么简单 以前直接是上述自定义格式就可以做停用词或者其他自定义词库的添加 谢谢 不知道您是否明白我的意思 您说的那个已经解决的我也看过 您好像建议用2.0.0的代码或者更新词库  我已经是2.1.0的词库个代码 本身加载都没有问题 就是自定义会报错

**Comment by pmgod8921** [comment]
maven提供的2.1.0包自带的词库是没有问题的 如果是上述格式的自定义词库 在加载自定义词库的时候 load方法 就会出现这种错误 哈哈 不知道是不是2.1.0还不是很完善 希望能帮忙看下 谢谢 😄 否则我就只能使用2.0.0了

**Comment by pmgod8921** [comment]
哈哈 大早上调试了一下 以前2.0.0的时候 会检查一下 自定义库中每行是否有 "/" 
![image](https://cloud.githubusercontent.com/assets/25093498/22005455/3f435646-dc9e-11e6-9628-d93b93efa567.png)
如果不存在就不会走else 这样就不会检查数组长度

2.1.0版本的时候 换成switch
![image](https://cloud.githubusercontent.com/assets/25093498/22005492/81ffbb6e-dc9e-11e6-8893-4340c5f46c36.png)
但是 如果类型为
![image](https://cloud.githubusercontent.com/assets/25093498/22005499/9205dd0e-dc9e-11e6-85e5-c6b3037984b5.png)
但是后面没有break 这样就会走 下面的
![image](https://cloud.githubusercontent.com/assets/25093498/22005504/a4b7ff9a-dc9e-11e6-89d1-f97c08011251.png)
这样如果长度不够就会报错
不知道是不是您有意这么做的！！！ 哈哈哈哈

**Comment by lionsoul2014** [comment]
这边还是建议将词库往后兼容下，方式很简单，"/"切分后没有四个长度的，补齐就可以了，使用支持正则表达式替换的文本编辑打开全部的自定义的词库，然后将"\n$" ”替换成"/null/null/null"即可。

例如如下格式的词库：
```
CJK_WORD
你好
我好
他好
大家好
```
通过替换就可以很方便的兼容。

2.1.0版本Jcseg开始了NLP计划，增加了切分的实体识别，实体被设计为可以完全在词库中自定义，类似于同义词，尤其是网址识别，增加了一些额外的词库，需要统一词库的格式验证，后面的版本都会需要这个格式作为基础。

**Comment by lionsoul2014** [comment]
并且，每次发布版本多少会有主词库的优化，比如，去掉一些无用词，增加一些新词条！

**Comment by pmgod8921** [comment]
谢谢您的回答 希望功能越来越强大 期待新版本的文本自动分类
