### ISSUE TITLE
自动加载词库path路径错误

### ISSUE THREAD

**Issue by ping199143** [lionsoul2014/jcseg#2]
jcseg-server.properties中配置两个以上词库路径，并都开启自动加载词库，线程读取错误路径
![0](https://cloud.githubusercontent.com/assets/4003733/15243933/2c798f8e-1931-11e6-8525-1052bec3ac3c.png)
![1](https://cloud.githubusercontent.com/assets/4003733/15243934/2c7a568a-1931-11e6-8772-29fee7fc4839.png)
![2](https://cloud.githubusercontent.com/assets/4003733/15243935/2c7c5192-1931-11e6-83d9-8bb6f6dc337e.png)

**Comment by lionsoul2014** [comment]
1，Jcseg-server.properties是给jcseg-server模块专用的配置文件，这个适合你将Jcseg当作服务器来使用，你可以参考下README中的说明文档！
2，如果你是要lucene,solr,elasticsearch或者自定义使用中配置多路径词库，你可以配置jcseg.properties配置文件，配置文件里面有说明：

{{{
#abusolte path of the lexicon file.
#Multiple path support from jcseg 1.9.2, use ';' to split different path.
#example: lexicon.path = /home/chenxin/lex1;/home/chenxin/lex2 (Linux)
#        : lexicon.path = D:/jcseg/lexicon/1;D:/jcseg/lexicon/2 (WinNT)
#lexicon.path=/java/JavaSE/jcseg/lexicon
lexicon.path = {jar.dir}/lexicon
}}

或者参考下http://git.oschina.net/lionsoul/jcseg/tree/v1.9.7-RC0/的开发帮助文档.pdf


Best
--lionsoul

ping199143 <notifications@github.com>于2016年5月13日周五 下午5:36写道：

**Comment by ping199143** [comment]
感谢耐心回复，ISSUE描述的不够清楚。我是用的是jcseg-server模块，Jcseg-server.properties配置两个词库lexicon和lex-epwk，都启用autoload。线程不稳定，偶尔出现图2中的异常情况。
![1](https://cloud.githubusercontent.com/assets/4003733/15278852/b987b42a-1b50-11e6-8ae7-46a7346841cd.png)
![2](https://cloud.githubusercontent.com/assets/4003733/15278853/b9b5dc60-1b50-11e6-9c91-e7d634570270.png)

**Comment by dongyado** [comment]
@ping199143  同一份配置情况下，会出现这个问题？

**Comment by ping199143** [comment]
是的，不稳定，偶尔才出现。

**Comment by lionsoul2014** [comment]
@ping199143 提交的pull requests中，是包含了修复该bug的的代码？

**Comment by ping199143** [comment]
没有哦  还没找到是什么原因

**Comment by lionsoul2014** [comment]
ok，谢谢！
