### ISSUE TITLE
请问一下该项目的后期发展计划

### ISSUE THREAD

**Issue by AnyListen** [lionsoul2014/jcseg#20]
该项目有没有一个todo list 呢；
很想知道下一步以及以后的规划

还请问一下，有没有计划做 实体识别、文本分类的功能；
此外目前的关键词提取还是有些不够准确，有没有计划考虑集成 TF/IDF 进行完善呢

**Comment by lionsoul2014** [comment]
1，CHANGES.md里面有个近期的计划，长期计划就是打造成一个NLP框架！
2，实体识别目前已经可以在NLPSeg中使用了，自己的机器人项目中已经用到，还在继续增加更多实体识别（升级信息：https://www.oschina.net/news/80814/jcseg-2-1-0）！
3，文本分类已经在计划中，实现时间目前不确定。
4，关键字/摘要提取目前用的pagerank算法的变体textrank，也是tf-idf的变体，比tf-idf算法要更准确！
算法只能解决80%的问题，关键字提取依赖Jcseg的词性标注，目前只是简单的基于词库，准确率还有待提高。

**Comment by lionsoul2014** [comment]
词性标注和实体识别目前都只是基于词库，需要训练一些语料库，综合周边的文字来做词性和实体的歧义去除来达到更精确的结果！

**Comment by AnyListen** [comment]
ok
可以把README.md 更新一下，介绍一下新功能及使用方法和效果

**Comment by lionsoul2014** [comment]
实体识别，还需要等下一个2.1.1版本发布才算一个产品级的应用功能，到时候会增加使用文档。
其他的成熟功能已经在README.md中增加使用文档说明了，效果这东西使用的场景不一样，不好描述！

**Comment by AnyListen** [comment]
可以 多谢
