### ISSUE TITLE
自动摘要

### ISSUE THREAD

**Issue by Bahramudin** [lionsoul2014/jcseg#21]
我试试了自动摘要，根本是没意义的算法，就不是完全是没法用，乱七八糟的。做就好好做，做个有意思的。这个是什么破玩意儿。浪费我们的时间了

**Comment by lionsoul2014** [comment]
哈哈，被痛吊了一顿！
目前的自动摘要还处于从原文提取段落的阶段，只适合一些特定的场合。
原本是打算建立语言模型，统计生成自动摘要，因为语言模型的语料训练比较费时一直搁着。
感谢你的关注和指正，会花更多时间去慢慢做好！

**Comment by zhangshanhai** [comment]
自动文章的摘要很难吧。

**Comment by lionsoul2014** [comment]
一个真正意义上的摘要提取，需要浏览全文，然后提取每小段的关键词条集合，然后通过训练好的语言模型组装出来（这个是最难的），目前jcseg的还仅仅是从文件中提取一段关键句子。
