### ISSUE TITLE
引号导致json反解析错误

### ISSUE THREAD

**Issue by luohuan02** [lionsoul2014/jcseg#22]
如果存在引号"，反斜杠\ ，会出现    "word":""" , "word":"\"这种词，然后json反解析出错，
在Word类toString方法
`sb.append("\"word\":\"").append(value).append('"');`
改为

```
        String tmpV = value;
        tmpV = tmpV.replaceAll("\\\\", "\\\\\\\\");
        tmpV = tmpV.replaceAll("\"", "\\\\\"");
        sb.append("\"word\":\"").append(tmpV).append('"');
```

解决
其它特殊字符类似

**Comment by lionsoul2014** [comment]
感谢反馈，目前就"和\字符，其他会影响的非打印字符默认过滤掉了！
已经修复并且提交！
