### ISSUE TITLE
词典词性有引号？  lex-chars.lex文件   礼/",nhs,n/li/null/31007

### ISSUE THREAD

**Issue by luohuan02** [lionsoul2014/jcseg#23]
如题，另外，第五个31007是做什么用的呢？

**Comment by lionsoul2014** [comment]
哈哈，Jcseg词库里面的词性我也是从很多其他语料库里面合并过来的，有的估计是标记错了，感谢反馈已经更改！
后面的31007是lex-chars.lex词库的特有属性，也是mmseg算法的核心之一，表示该词条的语素自由度，也就是统计出来的该词单独成词的频数，Jcseg内部的歧义去除决策依赖该数据！
