### ISSUE TITLE
ES5.3版本中不能指定为自定义分析器的tokenizer吗？

### ISSUE THREAD

**Issue by jia-dai** [lionsoul2014/jcseg#24]
看了源码貌似并没有注册相关的tokenizer，通过下面的（部分）代码建立index会出错："type":"illegal_argument_exception","reason":"Custom Analyzer [reuters] failed to find tokenizer under name [jcseg]"}]
我只是想在分词前去掉一些无意义的标签，不知用char_filter是否正确，还请指导如何设置最合适。
谢谢！

```javascript
						'analyzer' => [
							'reuters' => [
								'type' => 'custom',
								'char_filter' =>  ['html_strip', 'custom_char_filter'],
								'tokenizer' => 'jcseg',
								'analyzer' => 'jcseg_nlp',
								'filter' => ['lowercase', 'stop', 'kstem']
							]
						]
```

**Comment by lionsoul2014** [comment]
你这设置方式没问题，有注册tokenizer，码云上问到了同一个问题，可以参考下：http://git.oschina.net/lionsoul/jcseg/issues/51

**Comment by jia-dai** [comment]
已经参考设置好了。是我原来写的有问题。谢谢！
