### ISSUE TITLE
jcseg 如何解析外国姓名翻译后的中国人名？

### ISSUE THREAD

**Issue by pmgod8921** [lionsoul2014/jcseg#25]
例如：
“亨利·福特（1863年7月30日—1947年4月7日），出生于美国密歇根州韦恩郡的史普林威尔镇，他是汽车工程师，1915年，美国总统伍德罗·威尔逊接见福特，盛赞福特汽车公司，他是世界上第一位使用流水线大批量生产汽车的人。”
如何把 “亨利·福特” 这个人名在关键词中解析出来，而不是单独解析出 “亨利”
我的配置为：
![image](https://cloud.githubusercontent.com/assets/25093498/24852046/8a9c6b0e-1e08-11e7-8665-10f803393d2b.png)
请您帮忙解答一下，谢谢

**Comment by pmgod8921** [comment]
我关键词用的是COMPLEX_MODE 模式

**Comment by lionsoul2014** [comment]
Jcseg支持中文姓名的自动识别，但是对于英文翻译名不支持自动识别，你需要将“亨利·福特”放入词库中，也就是你的项目需要收集类似的词条，不然Jcseg会将他们切分开，配置没有问题。

**Comment by pmgod8921** [comment]
thx 谢谢
