### ISSUE TITLE
代码示例错误

### ISSUE THREAD

**Issue by lijian2033** [lionsoul2014/jcseg#27]
在Jcseg自动摘要/关键句子提取Api这部分中，代码：
Segment seg = SegmentFactory.createJcseg(
    JcsegTaskConfig.COMPLEX_MODE, 
    new Object[]{config, dic}
);
和SummaryExtractor extractor = new TextRankSummaryExtractor(seg, new SentenceSeg());中，
Segment应该为ISegment，SummaryExtractor应该为具体的TextRankSummaryExtractor类，请作者看一下是否正确？刚开始学这方面的知识，若提示错误敬请原谅！！！

**Comment by lionsoul2014** [comment]
哈哈，感谢关注：
1，确实少了一个I，应该是ISegment
2，SummaryExtractor是一个父接口，TextRankSummaryExtractor为SummaryExtractor的一个实现，可以这么用的。

已经更新，感谢反馈！
