### ISSUE TITLE
没有同义词啊

### ISSUE THREAD

**Issue by outerman** [lionsoul2014/jcseg#28]
看了一下词典，貌似只有“ 研究”这个demo用的词是有同义词的，其他的几乎没有啊。。。
什么时候能加上？或者我自己怎么添加同义词表比较好？

**Comment by lionsoul2014** [comment]
同义词需要自己整理，我自己整合部分同义词！现在同义词添加比较麻烦，即将发布的新版本会有统一的单独的同义词管理。
https://github.com/lionsoul2014/jcseg/tree/v1.9.7-RC0 这个tag版本下有个文档，可以参考下！

**Comment by EasyProgramming** [comment]
大大，如何在maven项目中自定义配置文件的位置？我使用'classpath/jcseg.properties'作为参数，一直提示路径错误。

**Comment by lionsoul2014** [comment]
v2.2.0-release版本已经统一了同义词的管理，README中增加了文档说明。
