### ISSUE TITLE
如何在MAVEN项目中自定义配置文件？

### ISSUE THREAD

**Issue by EasyProgramming** [lionsoul2014/jcseg#29]
大大，如何在maven项目中自定义配置文件的位置？我使用'classpath/jcseg.properties'作为参数，一直提示路径错误。

**Comment by lionsoul2014** [comment]
1，配置文件这个东西不是必须的，只是用于初始化JcsegTaskConfig
2，maven场景中使用jcseg的时候完全可以自己指定配置文件路径，参考README底部的代码demo。
3，如果是solr这种，直接将配置文件和jcseg-core-{version}.jar丢到同一目录就会自动加载

**Comment by EasyProgramming** [comment]
3Q
