### ISSUE TITLE
分词后能不能只返回自定义库中的词

### ISSUE THREAD

**Issue by pmgod8921** [lionsoul2014/jcseg#30]
例如 ：
长沙学点网络科技有限公司
自定义词库：(长沙是自定义词库中的词)
![image](https://cloud.githubusercontent.com/assets/25093498/26628288/1168627e-4630-11e7-8501-971afa0dfa89.png)
返回值：
长沙

如果可以 能不能详细说一下 怎么配置 谢谢

**Comment by lionsoul2014** [comment]
配置下jcseg.properties中的最大词长max_len，这个需要超过或者等于你的自定义词长，如果要识别“长沙学点网络科技有限公司”，max_len必须要至少为12。

如果是用在检索，建议保持max_len为5-7，过长会影响切分速度，检索对于词长长度影响不大

**Comment by pmgod8921** [comment]
首先 非常谢谢您的回答  但是好像您理解错了我的意思：
我的意思是 直接返回 自定义库中的词“长沙” 而不是 分词后 还会有 “网络” “科技” 之类的分词结果 】
分词后  我只要返回词是 “长沙” 这一个词 也就是自定义库中存在的词   不知道我说的您是否明白 哈哈

**Comment by lionsoul2014** [comment]
这个需要使用detect检测模式切分，REAMDE中有说明，然后把不要的词库删掉，留下你要保留的词库词条！
