### ISSUE TITLE
是否能识别新词？

### ISSUE THREAD

**Issue by Yevgnen** [lionsoul2014/jcseg#31]
如下文本： `在贾跃亭一手带领下，近几年一直在资本市场炮制概念，宣称打造体育、影业、手机、汽车等等生态的乐视，从未停止过烧钱模式。` 里，不论使用6种模式，`贾跃亭`都会被切分成 `贾`/`跃`/`亭`。

jieba分词里有新词识别功能，请问Jcseg是否有类似的功能？

**Comment by lionsoul2014** [comment]
新词识别目前就有中文姓名自动势必，上面这个功能是可以支持的：
```
在/nd 贾跃亭/nr 一手/a 带领/v 下/q ，/w 近几年/qt 一直/d 在/nd 资本市场/n 炮制/v 概念/n ，/w 宣称/v 打造/v 体育/n 、/w 影业/n 、/w 手机/n 、/w 汽车/n 等等/v 生态/n 的/u 乐/a 视/v ，/w 从未/d 停止/v 过/n 烧/n 钱/v 模式/n
```

姓名识别依赖lex-lname.lex，lex-dname-1.lex，lex-dname-2.lex三个词库，分别表示姓氏词库，双姓名第一次词库和双姓名第二字词库，jcseg本身没有收录很多类似词条，你需要维护这个词库来满足你的项目，在lex-dname-2.lex中加入“亭”字就可以识别该姓名了，如上！

**Comment by Yevgnen** [comment]
你好，感谢回答。我想问如果把大量单字加到lex-dname-*.lex里，对性能是否会有巨大影响？

**Comment by lionsoul2014** [comment]
再lex-dnamexxx.lex词库中加入大量的词条对性能没有任何影响，但是会对识别的结果造成一定干扰，丢入一定量会增加姓名识别的准确率，太多会有副作用，建议塞入从姓名语料中训练提取的词条！

**Comment by Yevgnen** [comment]
我把贾字加到了lex-dname-2.lex里面，也没能识别出来…

**Comment by Yevgnen** [comment]
`jcseg_icnname`也设置成了`true`.

**Comment by lionsoul2014** [comment]
哥们，把"亭"字加入lex-dname-2.lex词库，眼花了。。。

**Comment by lionsoul2014** [comment]
“贾跃亭”是一个双姓名（去掉姓氏），第一个字“跃”对应lex-dname-1.lex，第二个字“亭”对应lex-dname-2.lex词库

**Comment by Yevgnen** [comment]
是啊，我上面写了我手误，我加是正确的。

**Comment by lionsoul2014** [comment]
更改后尝试重新打包下再运行新的jar包，默认没有配置的情况下，jcseg找不到词库会加载jar包里面的词库，你测试的这个是没有加载你更改的词库而是jar里面的词库，你重新打包或者配置jcseg.properties加载你更改的词库！

**Comment by Yevgnen** [comment]
可以了…谢谢。

另外想问一句，我不想每次都重新打包，那就只能在配置文件里指定词典路径。但我又不想在里面写绝对路径，因为我现在在Python里调用，配置文件和文件我想放在项目的两个子目录下，可以支持相对路径么？我看里面注释是只能支持绝对路径…

**Comment by Yevgnen** [comment]
补充，绝对路径的一个问题是，比如我在MAC上，项目放在个人文件夹，总是以/Users/xxxx/git/project下，但放到linux下面就变成/home/yyyy/git/project了，那就只能把词典放去/usr/local这样的路径了。

**Comment by lionsoul2014** [comment]
支持相对路径的，在于你要找到这个相对路径的出发点，本身就是用的java的File查找，和jcseg无关！
