### ISSUE TITLE
如何不自动替换成英文标点？

### ISSUE THREAD

**Issue by Yevgnen** [lionsoul2014/jcseg#35]
数字后面的分号被替换成英文的分号了。

**Comment by lionsoul2014** [comment]
字母后面的标点都会自动全角转半角的，有利于识别例如：abc＠hij.ai等类似的东西。
如果要禁掉得更改ASegment的nextBasicLatin方法，把如下逻辑注释即可：

`if ( ch > 65280 ) ch -= 65248;`
