### ISSUE TITLE
jcseg如何添加整词本身进入拆词结果？

### ISSUE THREAD

**Issue by lexburner** [lionsoul2014/jcseg#37]
我想使用jcseg拆分单词，额外地，将单词本身也作为拆分词，我该如何添加这个功能？

**Comment by lionsoul2014** [comment]
还是没明白你的需求，得举个例子说明下

**Comment by lexburner** [comment]
@lionsoul2014 我们项目正在使用jcseg作为中文分词器，比如一段文本: ‘今天天气真不错’ 假设被拆分成了 今天  天气  真  不错 这四个词  因为我有一个特殊的需求  导致我需要在原有的四个词的基础上 额外增加句子本身作为索引，变成五个词：今天  天气  真  不错   今天天气真不错  这样搜索‘今天天气真不错’时  得分会变高  不太清楚怎么在jcseg的基础上修改TokenStream

**Comment by lexburner** [comment]
@lionsoul2014 希望能得到解答，研究jcseg两天了
