### ISSUE TITLE
如何去除部分同义词的相互引用？

### ISSUE THREAD

**Issue by lexburner** [lionsoul2014/jcseg#40]
iphone和苹果是近义词，但我只想搜索苹果时关联iphone，不想搜索iphone搜索出来一堆水果。

**Comment by lionsoul2014** [comment]
这个需要你自己来设置了，例如，可以增加一个配置，是否追加同义词。

**Comment by lionsoul2014** [comment]
理论上检索“iphone”，会同时检索“iphone”和"苹果"，比普通的“水果”打分肯定要高的，BM25模型排在前面的肯定是更“iphone”相关的。
