### ISSUE TITLE
关于nlp分词模式下，组合时间的问题

### ISSUE THREAD

**Issue by emily139617** [lionsoul2014/jcseg#41]
现在用的是2.1.1版本，nlp分词模式
1当遇到13:00-15:00这种时间段，似乎不能识别，自然与其他datatime类型组合也不能识别。所以想深究一下为什么这个时间段会识别，但是给定的entity是en，这个en是怎么给定的，假如我改成datatime类型是不是就可以与其他datatime类型组合一起识别
2组合时间测试的时候“张华平明天要结婚了”，分词结果只会有“张华平 明天”，而把结婚这么重要的词给省略。查看源码知道“明天”这个datatime 类型，会判断后面一个词的是否是datatime类型，是否要组合到一起，此时结婚是nv类型，不是datatime类型，所以不用组合，跳出组合循环代码的时候，没有把结婚这个词写回StringReader，因为源码里面是只有是null类型才会写回String流，所以稍微改了 一下源码，只要不是datatime类型，都要写会String流，后来测试成功验证了我的猜想。请问作者我的思路对否？

**Comment by lionsoul2014** [comment]
1，"时间段"目前jcseg无法识别，你可以通过先切分，然后再检测组合的形式组成这类词条。
2，这个是一个bug，已经在后期的版本中解决了，现在最新的版本是2.3.0，建议是直接使用master分之的代码，或者2.2.0-release的代码。
