### ISSUE TITLE
summary不是重点内容

### ISSUE THREAD

**Issue by xuanyuan1hao** [lionsoul2014/jcseg#42]
summary不是重点内容，都是doc里面的前面若干个字截取，没啥用。缺少语义分析，文章的关键句子提取才比较准确。

**Comment by lionsoul2014** [comment]
你理解的摘要应该是通过“文字的关键信息，然后按照语言模型自动生成的文字”。这个目前不支持，目前的摘要就是最核心句子周边的文字。。

**Comment by xuanyuan1hao** [comment]
嗯，我测试了几段文字，出来的结果都是从头部开始摘取前面100个字。
