### ISSUE TITLE
结合ES使用时词典更新问题

### ISSUE THREAD

**Issue by RicardoHWu** [lionsoul2014/jcseg#43]
我将Jcseg配置到ES里面，并开启词典自动更新，更新周期为1s，但实际使用中并没有更新。

以及ES作为一个分布式的搜索引擎，是否有考虑在ES中如何将新词同步到每个节点的词典中？

**Comment by lionsoul2014** [comment]
如果用的是最新的版本词库的自动更新应该是没问题的，老功能了，比较成熟了（系统不支持文件系统的just-in-time时间更新除外），确保以下工作：
1，更改词库。
2，将更改的词库的名字记载到lex-autoload.todo文件中，每个文件名一行。
3，jcseg是依据lex-autoload.todo中的更新来的，不是直接遍历全部的词库文件，因为jcseg可以支持多个目录，不同目录文件可以同名。

会在后续版本中增加给予http api的方式做词库的检测更新，也就解决了集群或者分布式的问题了，感谢反馈。

**Comment by RicardoHWu** [comment]
@lionsoul2014 因为设备环境的原因用的是ES 2.4.6，所以是找了2.0.0版本的jcseg-analyzer和jcseg-elasticsearch和2.2.0版本的jcseg-core更换为jdk1.7之后再重新编译使用的，不知道是不是这个原因导致无法使用自动更新

**Comment by lionsoul2014** [comment]
@RicardoHWu 和jdk的版本没关系，把你的系统环境发下，然后你的测试更改也发下，我这边试下！
