### ISSUE TITLE
jcseg2.2.0在elasticsearch5.6.5中access denied的问题!且安装了这个的节点能够正常运行但是数据基本是废了!

### ISSUE THREAD

**Issue by clark1230** [lionsoul2014/jcseg#44]
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[node-156][192.168.8.156:9300][indices:admin/analyze[s]]"}],"type":"access_control_exception","reason":"access denied (\"java.io.FilePermission\" \"plugins/jcseg/jcseg.properties\" \"read\")"},"status":500}

已经给文件添加足够的权限了。但是还是报文件读取没有权限的问题!装有jcseg的elasticsearch节点中没有索引数据，其他elasticsearch节点也不能同步索引数据!移除了jcseg后，这个问题没有了!

**Comment by lionsoul2014** [comment]
ES有自己的security规则，单纯的给相关文件权限还不够，需要设置es的权限：
1，增加security.policy增加对jcseg需要访问的文件的授权，例如：https://gitee.com/lionsoul/elasticsearch-jcseg/blob/master/security.policy
2，然后在config/jvm.options中增加对新增加的security.policy的导入：
```
# Define the security policy
-Djava.security.policy=security.policy
```

具体例子可以参考下：https://gitee.com/lionsoul/elasticsearch-jcseg

**Comment by lionsoul2014** [comment]
这边得到的之前的一些用户的反馈是，集群情况下，这样配置偶尔也会抛个异常，具体和版本有关，你可以试下。
最终解决方案就是把相关的资源全部打包到jar里面去，这样就完全没有权限问题了。

**Comment by lionsoul2014** [comment]
最新的master分之，通过es的安全的path方式访问资源了，无需再设置security.policy也不会存在权限问题了。
