### ISSUE TITLE
同义词或是中文数字转阿拉伯数字的问题

### ISSUE THREAD

**Issue by hupet** [lionsoul2014/jcseg#46]
您好，您的 jcseg 惠我良多，致上敝人万分感谢。
我在使用jcseg，有两个地方一直觉得有问题，就是当有同义词或是中文数字转阿拉伯数字的时候，所衍生出来的同义词或阿拉伯数字有以下问题：
1.其 endOffset 应该和原词的 endOffset 一样，而不应该是以衍生词的长度去定 endOffset。
2.衍生出来的词的 positionIncrement 应该是0，而不应该是1，否则在phrase search的时候会因为词的位置被衍生词隔断而查不到。
因为这两个值若与原词不同，会造成 phrase search 以及 highlight 的定位错误，请您协助确认，感谢您。

**Comment by lionsoul2014** [comment]
1，对于第一个问题，我测试过，如果endOffset设置为和原词一样，token本身会被截取，lucene系列的产品都是按照startOffset和endOffset来创建ByteRef
2，对于lucene内部的token来说，position必须后一个大于前一个，这个也测试过。

目前的同义词方案确实会造成highlight错误，这个需要研究借鉴下ES的同义词实现机制。

**Comment by hupet** [comment]
延续前面说明，在查询的时候，去分析他的query，以synonym filter去做查询分析：
```
GET my_index/_validate/query?explain
{
  "query": {
    "match_phrase": {
      "txt": "computer game"
    }
  }
}
```
结果如下：
```
{
  "valid": true,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "explanations": [
    {
      "index": "my_index",
      "valid": true,
      "explanation": """txt:"(computer pc) game""""
    }
  ]
}
```
同义词的 computer 和 pc 会以括号形成 or 的查询，因此不管查pc game或computer game都可以查得到
若以 jcseg 测试，查询分析：
```
GET jcseg_index/_validate/query?explain
{
  "query": {
    "match_phrase": {
      "txt": "人事管理部门的经理"
    }
  }
}
```
结果如下：
```
{
  "valid": true,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "explanations": [
    {
      "index": "jcseg_index",
      "valid": true,
      "explanation": """txt:"人事管理部门 人事管理部 人事部 的 经 理""""
    }
  ]
}
```
三个同义词因为position不同的关系，不会形成 or 的语法，其结果就是查「人事部的经理」查得到，
查「人事管理部门的经理」就查不到了，这样似乎失去了同义词的作用了。

**Comment by lionsoul2014** [comment]
感谢你提供的分析结果，我貌似明白了，给lucene的token.type我一直都是设置的word，同义词需要设置为SYNONYM，设置衍生词的offset和原词一致才不会截取，我这边改个版本试下。

**Comment by hupet** [comment]
还有positionIncrement，这个是恐怕才是同义词的关键，建议您参考一下Lucene的文件：https://lucene.apache.org/core/7_3_0/core/org/apache/lucene/analysis/tokenattributes/PositionIncrementAttribute.html
文件中一开始就说：Set it to zero to put multiple terms in the same position. This is useful ...
我记得我试过把type改成SYNONYM，结果是没用的，关键还是在position上。

**Comment by outshow** [comment]
不知道 作者 解决这个问题没有，貌似我也遇到这个问题。

**Comment by lionsoul2014** [comment]
backup: https://lucene.apache.org/core/8_0_0/core/org/apache/lucene/analysis/tokenattributes/PositionIncrementAttribute.html

**Comment by lionsoul2014** [comment]
@outshow @hupet 试试最新master分支的代码，给了一个修复提交，初测OK了。

**Comment by lionsoul2014** [comment]
经测试，该问题已经修复！
