### ISSUE TITLE
中央仓库无法下载2.3.0版本

### ISSUE THREAD

**Issue by huanghuazhang** [lionsoul2014/jcseg#48]
你好，想依赖2.3.0版本，报错无法下载相关依赖。查看中央仓库，发现/repositories/central/org/lionsoul/jcseg目录下，只更新到2.2.0版本，parent pom无法下载下来。是否发布到中央仓库时遗漏了？

**Comment by lionsoul2014** [comment]
哈哈，是的，前段时间sonotype出现问题了，老是提交不上去。可以下载仓库先在本地安装下。

**Comment by huanghuazhang** [comment]
好的，谢谢
