### ISSUE TITLE
关于ILexicon.CJK_WORD类型的疑问

### ISSUE THREAD

**Issue by koalton** [lionsoul2014/jcseg#49]
hi，咨询个关于使用自定义词典的问题。
场景：简单的电商商品搜索场景，自定义一个品牌词典（品牌可能包含中英混合情况）：brand.lex。词典类型采用了CJK_WORD，词典具体为：

```
CJK_WORD
骆驼
花花公子
```
在验证时候，发现在ADictionary类中的652行输出了格式信息不准确，具体代码是会通过特定分隔符把词典每行进行分割，分割的数组长度小于4就会出现此问题：
```java
wd = line.split("\\s*/\\s*");
                if ( wd.length < 4 ) {    //format check
                    System.out.println("Word: \"" + wd[0] + "\" format error. -ignored");
                    continue;
                }
```

仔细看了下这个格式需要变为以下才可以通过：

```
CJK_WORD
骆驼///null
花花公子///null
```
可以请问下这么设计是为了解决什么问题吗？或者说，我的场景，适合用哪种词典类型？

**Comment by lionsoul2014** [comment]
https://gitee.com/lionsoul/jcseg/issues/ILHRF
