### ISSUE TITLE
Missing jcseg pom for 2.3.0 in central repository

### ISSUE THREAD

**Issue by shoukunhuai** [lionsoul2014/jcseg#51]
Maven report build fail when upgrade to 2.3.0 

>ERROR Could not find artifact org.lionsoul:jcseg:pom:2.3.0

**Comment by shoukunhuai** [comment]
Close as this is a known issue on gitee

**Comment by lionsoul2014** [comment]
Try the latest jcseg version 2.4.0. i've tried many times to upload the jcseg 2.3.0 to sonatype and all failed.
