### ISSUE TITLE
本机的外网网址为什么不支持

### ISSUE THREAD

**Issue by shijunti19** [lionsoul2014/jcseg#52]
我测试了各种模式，都存在问题
1.换行没了，这个我估计我只能逻辑处理
2.遇到￥（各种特殊字符）会丢失，这个我无法处理
3.全部变成了小写，有没有选项保证词不变！
4.网址也被拆分了，这个我用代码也实现了，还原不过不完美！

总之，我实现不了，只能纯文字的处理似乎还行！

**Comment by lionsoul2014** [comment]
1，换行符和空格都默认去掉了，不知道什么需求会需要换行符和空格。
2，保留标点可以在jcseg.properties中自己配置。
3，默认全部转成小写了，这个只能改代码。
4，网址的识别和NER是NLP模式的工作。


```shell
$/w/null 3.5美金/q/nuc_currency.usd 可以/a/null 购买/v/null 一个/q/null footbal/en/null ,/w/null https://github.com/lionsoul2014/jcseg/issues/52/en/url
```

```shell
中国/ns/place.nation 版本/q/null 的/u/null github/en/null 请/v/null 访问/v/null http://gitee.com//en/url
```

**Comment by shijunti19** [comment]
@lionsoul2014 那个锤子手机不是有个大爆炸嘛！然后我做了一个手机编辑器，把文章炸成一个个词组，然后点击可以给文字加颜色，编辑什么的，找了大部分分词的，你的比较好用，但是就是分词出来不是原文，缺上面这些东西

**Comment by lionsoul2014** [comment]
@shijunti19 两份数据隔离显示就OK了，分词结果统一小写，阅读方便，反而是个好体验。
