### ISSUE TITLE
BUILD FAILED 2.4.0

### ISSUE THREAD

**Issue by zeg** [lionsoul2014/jcseg#54]
ant all
Buildfile: build.xml

init:
     [echo] ------------------------------------------------------------
     [echo] ----------BUILDING JCSEG PACKAGE----------------------------
     [echo]
    [mkdir] Created dir: /www/git/jcseg-2.4.0-release/src
    [mkdir] Created dir: /www/git/jcseg-2.4.0-release/classes
    [mkdir] Created dir: /www/git/jcseg-2.4.0-release/doc
     [echo] Coping sources of jcseg-core/src/main/java to /www/git/jcseg-2.4.0-r                                              elease/src
     [copy] Copying 50 files to /www/git/jcseg-2.4.0-release/src
     [echo] Coping lexicons to /www/git/jcseg-2.4.0-release/classes
     [copy] Copying 29 files to /www/git/jcseg-2.4.0-release/classes/lexicon
     [echo] Coping sources of jcseg-analyzer to /www/git/jcseg-2.4.0-release/src
     [copy] Copying 4 files to /www/git/jcseg-2.4.0-release/src
     [echo] Coping sources of jcseg-elasticsearch to /www/git/jcseg-2.4.0-releas                                              e/src
     [copy] Copying 10 files to /www/git/jcseg-2.4.0-release/src
     [echo] Coping sources of jcseg-server to /www/git/jcseg-2.4.0-release/src
     [copy] Copying 60 files to /www/git/jcseg-2.4.0-release/src

BUILD FAILED
/www/git/jcseg-2.4.0-release/build.xml:60: Warning: Could not find file /www/git                                              /jcseg-2.4.0-release/jcseg.properties to copy.

Total time: 0 seconds

**Comment by lionsoul2014** [comment]
用maven编译吧，ant脚本已经很久没更新了。

**Comment by zeg** [comment]
mvn compile ? 编译成功之后结果在哪
并没有看到jcseg-server/target/jcseg-server目录

**Comment by zeg** [comment]
嗯……搞定了……
