### ISSUE TITLE
一类英文分词错误的问题

### ISSUE THREAD

**Issue by joock** [lionsoul2014/jcseg#56]
版本号：2.0及以上
英文（java异常日志的package名）：com.com.com.com.com.com.com.com.com.com.com.java.java.java.java.java.java.java
例如：
jcseg~tokenizer:complex>> com.com.com.com.com.com.com.com.com.com.com.java.java.java.java.java.java.java
分词结果：
com.com.com.com.com.com.com.com.com.com.com.java.java.java.java.j/en com/en com/en com/en com/en com/en com/en com/en com/en com/en com/en com/en java/en java/en java/en java/en ava.java.java/en ava/en java/en java/en
其中错误的分词：com.com.com.com.com.com.com.com.com.com.com.java.java.java.java.j/en ava.java.java/en ava/en

**Comment by lionsoul2014** [comment]
嗯，这个不算一个错误。Jcseg对英文的分词就是通过标点和空格，并没有像中文一样依赖词库，这个切分就是这个结果。

你可以在jcseg.properties中把jcseg.keeppunctuations = @#%.&+ 的'.'给去掉，就会切分成com和java了。
jcseg.keeppunctuations控制者保留标点，之中的标点会当做普通英文字符保留。

**Comment by joock** [comment]
2.*版本下，去掉jcseg.keeppunctuations = @#%.&+ 中的'.'之后，确实没问题了。:)
但是，在jcseg.keeppunctuations的配置相同的情况下，2.*版本下**java这个单词被分成了j和ava**，在1.9*的版本下没有这个问题，是命中了字母长度（66个）的一个规则？

com.com.com.com.com.com.com.com.com.com.com.java.java.java.java.**j/en**
**ava**.java.java/en
