### ISSUE TITLE
2.4.1版本 match_phrase 查询查不到结果

### ISSUE THREAD

**Issue by outshow** [lionsoul2014/jcseg#57]
比如 使用“儿童节”作为文本，建立索引是和搜索的时候 都使用 jcseg_search 分析器。

然后是用 match_phrase 方式 通过 “儿童” 搜索不到文本，但“儿、童、节、童节” 4个搜索词都可以搜到，通过分析发现应该是 分词器分词顺序有问题导致。

`{
    "analyzer": "jcseg_search",
    "text":"儿童节"
}'
{
  "tokens" : [
    {
      "token" : "儿",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "儿童",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 1
    },
    {
      "token" : "儿童节",
      "start_offset" : 0,
      "end_offset" : 3,
      "type" : "word",
      "position" : 2
    },
    {
      "token" : "童",
      "start_offset" : 1,
      "end_offset" : 2,
      "type" : "word",
      "position" : 3
    },
    {
      "token" : "节",
      "start_offset" : 2,
      "end_offset" : 3,
      "type" : "word",
      "position" : 4
    }
  ]
}`

`{
    "analyzer": "jcseg_search",
    "text":"儿童"
}'
{
  "tokens" : [
    {
      "token" : "儿",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "儿童",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 1
    },
    {
      "token" : "童",
      "start_offset" : 1,
      "end_offset" : 2,
      "type" : "word",
      "position" : 2
    }
  ]
}`

两个文本的分词顺序不一致导致搜不到文本

**Comment by lionsoul2014** [comment]
分词顺序和文档是否匹配没有关系。https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html

对于你的这个场景：
1. 不使用search模式，search本身就是这么个分词方式。
2. 使用term或者terms查询。

**Comment by outshow** [comment]
如果不使用search模式，业务上需要搜索单个字的场景，可能搜不出结果。
使用term或者 terms不能做到模糊搜索的效果。

**Comment by lionsoul2014** [comment]
这超出了分词的范畴，term多了性能问题都来了，es的phrase match很少用，给不出啥好建议了！

**Comment by outshow** [comment]
嗯，我再看看还有没有其他办法，谢谢啊！
